version: "3"

services:
  streamlit:
    build:
      context: .
      dockerfile: ./streamlit/Dockerfile
    restart: always

  nginx:
    image: nginx:latest # https://hub.docker.com/_/nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/templates/default.conf.template
      # - ./nginx/nginx-acme.conf.template:/etc/nginx/templates/default.conf.template
      - ./certbot/config:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - streamlit
    environment:
      DOMAIN: ${DOMAIN}

  authproxy:
    build:
      context: .
      dockerfile: ./oauth2proxy/Dockerfile
    ports:
      - 4180:4180
    environment:
      TENANT_ID: ${TENANT_ID}
      APPLICATION_CLIENT_ID: ${APPLICATION_CLIENT_ID}
      APPLICATION_CLIENT_SECRET: ${APPLICATION_CLIENT_SECRET}
      REDIRECT_URL: ${REDIRECT_URL}
      COOKIE_SECRET: ${COOKIE_SECRET}
